image: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - build\CIBuild.cmd -configuration Debug

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - build\CIBuild.cmd -configuration Release

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # debug test results
  - path: artifacts\Debug\TestResults
    name: Debug_Test_Results

  # debug build log
  - path: artifacts\Debug\log
    name: Debug_Logs

  # release test results
  - path: artifacts\Release\TestResults
    name: Release_Test_Results

  # release build log
  - path: artifacts\Release\log
    name: Release_Logs

  # release nuget packages
  - path: 'artifacts\Release\bin\Microsoft.DotNet.Analyzers.Compatibility\*.nupkg'
    name: Nuget_Packages
